In [41]:
import tensorflow as tf
import numpy as np

# Ejemplo Funcion Lineal

In [42]:
X_val = tf.convert_to_tensor(np.array([2,4,6,8,10,12]), dtype='float32')

b_const = tf.constant([2.0])

m_const = tf.constant(3.0)

Prediccion 

$$Y = mx + b$$

In [43]:
y_data = tf.add(tf.multiply(m_const,X_val),b_const)

print(y_data)

tf.Tensor([ 8. 14. 20. 26. 32. 38.], shape=(6,), dtype=float32)


# Ejemplo Red Neuronal Convolucional

In [44]:
X_data = tf.convert_to_tensor(np.random.rand(1,4,4,1), dtype='float32')

filtro = tf.constant(0.25, shape=[2,2,1,1])

strides = [1,2,2,1]

mov_avg_layer = tf.nn.conv2d(X_data, filtro, strides,padding='SAME', name ='Moving_avg_windows'  )

Dimension de salida:

$$\frac{dim entrada - dim filtro + 2 padding}{stride} + 1 $$

La función tf.nn.conv2d() en TensorFlow realiza una operación de convolución 2D sobre una entrada. Aquí tienes una explicación detallada de sus principales parámetros:

input:
Descripción: Este es el tensor de entrada sobre el cual se realizará la convolución.
Forma: El tensor debe tener una forma [batch, height, width, channels], donde:
batch es el número de imágenes en el lote.
height es la altura de la imagen.
width es el ancho de la imagen.
channels es el número de canales de la imagen (por ejemplo, 3 para imágenes RGB).

filters (también llamado weights o kernel):
Descripción: Este es el tensor que contiene los filtros (o kernels) utilizados para la convolución.
Forma: El tensor de filtros debe tener una forma [filter_height, filter_width, in_channels, out_channels], donde:
filter_height es la altura del filtro.
filter_width es el ancho del filtro.
in_channels es el número de canales de entrada (igual al número de canales de la entrada).
out_channels es el número de filtros o mapas de características (es decir, el número de canales de salida).

strides:
Descripción: Este parámetro especifica el paso de la convolución a lo largo de cada dimensión de la entrada.
Forma: Es una lista de cuatro valores [1, stride_height, stride_width, 1].
1 es el paso en la dimensión del lote (se mantiene como 1).
stride_height es el paso a lo largo de la altura de la imagen.
stride_width es el paso a lo largo del ancho de la imagen.
1 es el paso en la dimensión del canal (se mantiene como 1).

padding:
Descripción: Este parámetro especifica el tipo de relleno a aplicar a la entrada.
Valores posibles:
'SAME': Aplica un relleno de manera que la salida tenga la misma dimensión espacial que la entrada.
'VALID': No aplica relleno, por lo que la dimensión espacial de la salida se reduce.

In [45]:
# Capa a medida, reduce las dimesiones, realiza unas multiplicaciones de matrices
#y aplica una funcion sidmoide

def custom_layer(input_matrix):
    input_matrix_squeezed = tf.squeeze(input_matrix)
    A = tf.constant([[1.,2.],[3.,4]])
    b = tf.constant(1., shape = [2,2])
    temp1 = tf.matmul(A, input_matrix_squeezed)
    temp2 = tf.add(temp1, b) ## Ax+b
    return tf.sigmoid(temp2)

#aplica la funcion a la capa
with tf.name_scope('Custom_Layer') as scope:
    customlayer1 = custom_layer(mov_avg_layer)

In [46]:
#capa de salida
print(customlayer1)

tf.Tensor(
[[0.942152   0.93658537]
 [0.99312407 0.99367476]], shape=(2, 2), dtype=float32)


In [47]:
#Salida de la convolucion
print(mov_avg_layer)

tf.Tensor(
[[[[0.39213204]
   [0.67176855]]

  [[0.69910824]
   [0.51038855]]]], shape=(1, 2, 2, 1), dtype=float32)


# Tensorboard

In [55]:
#Ejemplo de codigo para usar tensorboar con una RNA

#grafica la presicion a lo largo de las epocas

mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

def create_model():
  return tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
  ])

In [56]:
model = create_model()
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model.fit(x=x_train, 
          y=y_train, 
          epochs=5, 
          validation_data=(x_test, y_test), 
          callbacks=[tensorboard_callback])

c:\Users\jrgui\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 27s 11ms/step - accuracy: 0.8915 - loss: 0.3644 - val_accuracy: 0.9683 - val_loss: 0.1006
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 38s 10ms/step - accuracy: 0.9699 - loss: 0.1000 - val_accuracy: 0.9696 - val_loss: 0.0966
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 10ms/step - accuracy: 0.9783 - loss: 0.0692 - val_accuracy: 0.9755 - val_loss: 0.0723
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.9848 - loss: 0.0513 - val_accuracy: 0.9758 - val_loss: 0.0816
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 10ms/step - accuracy: 0.9875 - loss: 0.0396 - val_accuracy: 0.9775 - val_loss: 0.0749


Para poder ver las gráficas:

Se debe correr en la shell(terminal) 
>tensorboard --logdir tensorboard/

Luego colocar lo siguiente dentro de un navegador:
http://localhost:6006/
