In [38]:
import tensorflow as tf
import numpy as np

# Funcionamiento de TensorFlow

# Tensores y Variables

- Tensores son estructura en la que se basa tensorflow, son vectores en espacios mas grandes

- Variables son parametros del modelo, optimiza el resultado del algoritmo y donde se recibe la informacion.



In [39]:
# Variables

my_var = tf.Variable(tf.zeros([2,2]))

#TensorFlow 2.x ejecuta por defecto en modo "eager execution", 
# lo que significa que las operaciones se ejecutan de inmediato. 
# No necesitas crear una sesión para variables y placeholder

In [40]:
val = np.random.rand(2,2)

#Primera manera
y1 = tf.convert_to_tensor(val, tf.float32)

# Segunda manera, se guarda el arreglo en un placeholder 
# y se puede pasar por una funcion antes de guardar
 
def my_function(x):
    return tf.identity(x) 

y2 = my_function(tf.convert_to_tensor(val, dtype=tf.float32))

print(y1, y2)


tf.Tensor(
[[0.7495489  0.13788363]
 [0.20412026 0.58233213]], shape=(2, 2), dtype=float32) tf.Tensor(
[[0.7495489  0.13788363]
 [0.20412026 0.58233213]], shape=(2, 2), dtype=float32)


# Tensores

In [51]:
# Tensores fijos

#Tensor constantes
const = tf.constant([1,2,3], dtype='float32') # sirve para pasar arreglos a tensores

const_t = tf.convert_to_tensor([1,2,3,4,5], dtype='float32') #transforma lista u otras arreglos a tensores

#para saber las dimensiones del tensor
print(const_t.shape) 

#Tensor de arreglo de ceros de 2filas, 6columnas y 3profundidad
zero_t = tf.zeros([3,2,6])

#Tensor de arreglo de unos de 3filas, 2columnas
ones_t = tf.ones([3,2])

#Tensor de 10 con dimensiones 2filas, 2columnas y 2profundidad
const_fill = tf.fill([2,2,2],10)

print(const)

(5,)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [42]:
#Tensores por tamaño similar

#crea un tensor de ceros del tamaño del tensor const
zeros_sim = tf.zeros_like(const)

ones_sim = tf.ones_like(const_fill)

In [43]:
# Tensor en forma de secuencia

#Crea un tensor de valores que inician en 0, terminan en 1 y tienen 5 intervalos del mismo tamaño
sec_t = tf.linspace(0, 1, 5)

#crea un tensor de valores que comienzan en 0, ternimanen 1 y tienen un paso de 0.20
range_t = tf.range(0, 1, 0.20)


In [44]:
#Tensores aleatorios

#Crea tensor [2,2] lleno con valores aleatorios uniformes entre 0 y 1
random_t = tf.random.uniform([2,2], 0, 1)

#Crea tensor [2,2] lleno con valores aleatorios normales entre 0 y 1
random_normal_t = tf.random.normal([2,2], 0, 1)


## Matrices

In [82]:
A = tf.convert_to_tensor(np.array([[1,2,3],[4,5,6],[7,8,9]]), dtype='float32')

B = tf.convert_to_tensor(np.array([[1,2,3],[6,5,4],[9,8,9]]), dtype='float32')

#transpuesta
A_trasp = tf.linalg.matrix_transpose(A)

#Suma de matrices
C = tf.add(A,B)

#producto de matrices
D = tf.matmul(A,B)

#inversa de una matriz
E = tf.linalg.inv(D)

#Da casi la matriz identidad, difiere por los decimales
#usando la inversa de Moore-Penrose
I = tf.matmul(B,tf.linalg.pinv(B))

#Norma de un vector, matriz, tensor
norm = tf.linalg.norm(I) # da la norma de la matriz identidad sgrt(3)

#Determinante
E_inv = tf.linalg.det(E)

#Producto cruz
H = tf.linalg.cross([5,2,-1],[0,-1,4])

#Autovalores
F = tf.linalg.eigvalsh(A)

#Autovectores
G = tf.linalg.eigvals(A)

In [83]:
print(H)
print(norm)

tf.Tensor([  7 -20  -5], shape=(3,), dtype=int32)
tf.Tensor(1.7320508, shape=(), dtype=float32)


# Operaciones

In [85]:
#Aritmeticas

x = tf.constant(3)
y = tf.constant(5)

#tambien se puede realizar con x,y
suma = tf.add(8,4)
resta = tf.subtract(8,4)
multi = tf.multiply(8,4)
div = tf.truediv(8,4)
resto = tf.math.mod(8,4)



In [115]:
# Funciones

#Creo un tensor para usar
x = tf.convert_to_tensor([-3,-2,-1,0,1,2,3], dtype='float32') 

#valor absoluto
abs = tf.abs(x)

#redondeo normal
red = tf.round(6.4)
#para arriba
red_up = tf.math.ceil(6.4)
#para abajo
red_down = tf.math.floor(6.4)

#seno
seno = tf.sin(x)

#exponencial
exp = tf.exp(x)

#cambio de signo
camb = tf.negative(x)

#potenciacion
pot = tf.pow(x,2)

#raiz cuadrada
raiz = tf.sqrt(x) #no da error para los negativos, coloca nan

#devualve el signo de cada elemento
signo = tf.sign(x)



In [120]:
# Funciones de Activacion

import tensorflow.nn as nn

#relu
relu = nn.relu(x)

#sigmoide
sigm = nn.sigmoid(x)

#tangente hiperbolica
tangh = nn.tanh(x)

#softsing
ss = nn.softsign(x)

# Estructura del Modelos

In [46]:
#Definir estructura del modelo-algoritmo
# Se define por un grafo computacional

#Para la funcion y=mx+n

#se pudiera expresar de la siguente manera:
# y_pred = tf.add(tf.multiply(m_matix, x_input), n_vector)


# Funcion de Pérdida - Cálculo de error

In [47]:
#Declarar la funcion de perdidas

#error cuadrado medio - MSE
#loss = tf.reduce_mean(tf.square(y_actual-y_pred))